### ISSUE TITLE
Meta Issue: Improve picking

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#3100]
Improve picking by addressing the following:
- [x] Point picking uses `vtkPicker` and we should instead use [vtkHardwareSelector](https://vtk.org/doc/nightly/html/classvtkHardwareSelector.html).
- [ ] Enable selection picking for blocks (requires #2941)
- [x] #2412
- [ ] #1335
- [x] #2520 (revisit after #2948)
- [x] #2578
- [x] #3027
- [x] #3317
- [x] #3550
- [x] https://github.com/pyvista/pyvista/discussions/3703
- [x] https://github.com/pyvista/pyvista/issues/3915

**Comment by adam-grant-hendry** [comment]
@akaszynski Could you please add #3317 to this list?

**Comment by banesullivan** [comment]
Done

**Comment by banesullivan** [comment]
Closing this issue after #4254 addressed most all of these. The only remaining unadressed task is:

> Enable selection picking for blocks (requires https://github.com/pyvista/pyvista/pull/2941)

@akaszynski, if this is still a priority, let's track as a standalone issue. Otherwise, I think it's fair to close this meta issue
